[build]
  publish = "."

[[redirects]]
  from = "https://www.gabrielaarghiroiu.ro/*"
  to = "https://gabrielaarghiroiu.ro/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/blog/*"
  to = "https://cabinet-psihologic-gabriela.onrender.com/blog/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/admin*"
  to = "https://cabinet-psihologic-gabriela.onrender.com/admin:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "https://cabinet-psihologic-gabriela.onrender.com/api/:splat"
  status = 200
  force = true
